### ISSUE TITLE
Content on screen dissappears

### ISSUE THREAD

**Issue by cjrupak** [kempsteven/vue-html2pdf-demo#11]
Hey,

Thank you for this awesome script/component.

The issue that I am facing is when I wrap my component containing PDF content inside **vue-html2pdf**, the content disappears from the DOM but it is generating the PDF correctly upon button click.

```
<vue-html2pdf
   :show-layout="false"
   :float-layout="true"
   :enable-download="true"
   :preview-modal="true"
   :paginate-elements-by-height="1400"
   filename="some_file_name"
   :pdf-quality="2"
   :manual-pagination="false"
   pdf-format="a4"
   pdf-orientation="portrait"
   pdf-content-width="800px"
   ref="html2Pdf"
>
     <dashboard slot="pdf-content" />
</vue-html2pdf>
```

The page is blank but the PDF is generating. Please take a look at **Before** and **After** images below.

### Before

<img width="2560" alt="Screenshot 2020-10-05 at 4 07 54 PM" src="https://user-images.githubusercontent.com/40754163/95070649-0e008980-0726-11eb-874a-8e0e7cdf2f4c.png">

### After
<img width="2560" alt="Screenshot 2020-10-05 at 4 04 58 PM" src="https://user-images.githubusercontent.com/40754163/95070586-f6290580-0725-11eb-851e-407baf5cb78d.png">

Thanks!

**Comment by kempsteven** [comment]
try setting :float-layout to false

**Comment by cjrupak** [comment]
Hi,

Thank you for the quick response.

Setting :`float-layout` to **false** did help but then it was also displaying the layout for PDF beneath the browser view. So it was rendering both the browser and PDF views at the same time.

I found another way or a workaround you can say but tell you the truth I really don't know if this is how it is suppose to be in the first place but I added the component containing the content on the top of vue-html2pdf component, like below:

```
<dashboard  /> <!--/ Here is the component for browser view -->
<vue-html2pdf
        :show-layout="false"
        :float-layout="true"
        :enable-download="true"
        :preview-modal="true"
        :paginate-elements-by-height="1400"
        filename="upgame"
        :pdf-quality="2"
        :manual-pagination="true"
        pdf-format="a4"
        pdf-orientation="portrait"
        pdf-content-width="800px"
        ref="html2Pdf"
      >
        <dashboard slot="pdf-content" /> <!--/ same component for PDF with slot attribute -->
</vue-html2pdf>
```

If this is how it was meant to be then I made the dumbest mistake ever. (LOL)

Anyways, with the above change, things are working for me.

Cheers!

**Comment by kempsteven** [comment]
Yeah hahah, It's either you use the props `float-layout` to show the `pdf-content` or just use the same component on the page.

Anyways cool, glad everything worked for you!
