### ISSUE TITLE
Pdf Content  Is showing like a Image?

### ISSUE THREAD

**Issue by ramnithik** [kempsteven/vue-html2pdf-demo#3]

**Comment by kempsteven** [comment]
vue-html2pdf uses [html2pdf.js](https://github.com/eKoopmans/html2pdf.js) under the hood and one of the know issues of html2pdf.js is it renders all content into an image, then places that image into a PDF

you can see it here
https://github.com/eKoopmans/html2pdf.js?files=1#known-issues
